# Generated by Django 5.2.7 on 2025-11-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_budgets',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Orçamentos criados: '),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('master', 'Master')], default='free', max_length=10, verbose_name='Plano'),
        ),
    ]
