# Generated by Django 5.2.7 on 2025-11-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_accept_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accept_email',
            field=models.BooleanField(default=False, verbose_name='Aceito receber emails'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accept_terms',
            field=models.BooleanField(default=False, verbose_name='Aceito os termos '),
        ),
    ]
