# Generated by Django 5.2.7 on 2025-10-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_client_options_client_city_client_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('inativo', 'Inativo'), ('ativo', 'Ativo')], default='ativo'),
        ),
    ]
