# Generated by Django 5.2.7 on 2025-10-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, default='Cidade não informada', max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='complement',
            field=models.CharField(blank=True, default='sem complemento', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='neighborhood',
            field=models.CharField(blank=True, default='Bairro não informado', max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, default='s/n', max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, default='Estado não informado', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(blank=True, default='CEP não informado', max_length=15, null=True, verbose_name='CEP'),
        ),
    ]
