# Generated by Django 5.2.7 on 2025-10-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_client_country_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='client',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='client',
            name='number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='street',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zipcode',
        ),
    ]
