# Generated by Django 5.2.7 on 2025-10-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_budget_client_alter_budget_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='value',
        ),
    ]
