# Generated by Django 5.2.7 on 2025-10-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_budget_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='description',
        ),
    ]
