# Generated by Django 5.2.7 on 2025-10-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_budget_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Orçamento Ativo'),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='services',
            name='subtotal_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade'),
        ),
    ]
