# Generated by Django 5.2.7 on 2025-11-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_budget_is_active_budget_total_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='obs',
            field=models.TextField(default='', verbose_name='Observaçoes'),
            preserve_default=False,
        ),
    ]
