# Generated by Django 5.2.7 on 2025-11-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_budget_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='subtotal_budget',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal'),
        ),
    ]
