# Generated by Django 5.2.7 on 2025-11-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_services_subtotal_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='services',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário'),
        ),
    ]
