# Generated by Django 5.2.7 on 2025-11-02 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_services_quantity_alter_services_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Material')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário')),
                ('subtotal_material', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.budget')),
            ],
        ),
    ]
