# Generated by Django 5.2.7 on 2025-11-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de exclusão'),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de exclusão'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
