# Generated by Django 5.2.7 on 2025-11-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_budget_deleted_at_client_deleted_at_client_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
    ]
