# Generated by Django 5.2.7 on 2025-11-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_client_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='subtotal_budget',
            new_name='subtotal_services',
        ),
    ]
